### ISSUE TITLE
.hooks and .ready extensions

### ISSUE THREAD

**Issue by teppokoivula** [BernhardBaumrock/RockMarkup#2]
Hey Bernhard! Thought I'd mention this, in case you consider it an issue.

The format for the hook files are some-file.hooks and some-file.ready, but the problem here is that since these are not typical PHP extension or ones recognised by ProcessWire, these files will likely be publicly readable with direct URL.

As such, I think it would be best to either use a .php extension instead (.hooks.php and .ready.php), or alternatively add a .htaccess file to the module directory preventing direct access.

**Comment by BernhardBaumrock** [comment]
Thx Teppo, totally missed that!! Seems I got no notification about that issue. I'll fix it asap :)

**Comment by teppokoivula** [comment]
No worries! Just glad that this is being dealt with now :)

**Comment by BernhardBaumrock** [comment]
Thx @teppokoivula just fixed that :) https://github.com/BernhardBaumrock/RockMarkup2/commit/e9c0bcf43d84078e36ee9e219d19b911c180e168

**Comment by teppokoivula** [comment]
Great, thanks! :)
